_prefs: 
  mapid: devseed.3a52f684
  saveCenter: true
_properties: 
  bridge: 
    "group-by": layer
attribution: "<a href=\"http://www.worldpop.org.uk/\" target='_blank'>&copy; WorldPop</a><a href='https://www.mapbox.com/about/maps/' target='_blank'>&copy; Mapbox &copy; OpenStreetMap</a> <a class='mapbox-improve-map' href='https://www.mapbox.com/map-feedback/' target='_blank'>Improve this map</a>"
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - 89.6237
  - 22.6951
  - 9
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 14
minzoom: 2
name: worldpop - basemap - secondtake
source: "mapbox:///devseed.isnka9k9,devseed.068dce72,devseed.nepal-admin-boundaries,mapbox.mapbox-streets-v5,mapbox.mapbox-terrain-v2"
styles: 
  - style.mss
  - population.mss
  - labels.mss
  - roads.mss
  - terrain.mss
template: ''
